### ISSUE TITLE
Update OpenMPT to current

### ISSUE THREAD

**Issue by glennlunder** [demozoo/cowbell#27] opened 2022-05-05 05:32 UTC
To support several new formats that were added since we last built (at least symmod, dsym, stx, mus, fmt).

See the following interaction from Discord;

sagamusix — 17/04/2022
should say though that demozoo / cowbell is using by now a pretty outdated libopenmpt version so it's quite possible that the bug has already been fixed
menace — 17/04/2022
I feel like we refreshed not-that-long-ago, but then again that is based off of my memory, and I am a VERY OLD MAN.
sagamusix — 17/04/2022
the last official update in the cowbell repository was two years ago :) an eternity in libopenmpt-land

**Comment by sagamusix** [comment] 2022-06-29 19:48
Duplicate of #25

**Comment by gasman** [comment] 2022-06-29 23:58
Upgraded to 0.6.4 in 7bb47ee88ee7ebe77f0f9858c5b19e636b66cd8e.

**Closed as completed by gasman** 2022-06-29 23:58 UTC
Labels: enhancement
